version: '3.8'

services:
  # Backend services
  backend-app:
    build:
      context: ./backend
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html:rw
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-ChangeMe}@backend-database:5432/${POSTGRES_DB:-app}
    depends_on:
      - backend-database
    networks:
      - rextract-network

  backend-database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - rextract-network

  backend-nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/html/public
    depends_on:
      - backend-app
    networks:
      - rextract-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - rextract-network

volumes:
  db-data:


networks:
  rextract-network:
    driver: bridge
