<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250626054744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE ingredients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_4B60114F5E237E06 ON ingredients (name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE recipe_ingredients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity VARCHAR(255) NOT NULL, unit VARCHAR(255) NOT NULL, ingredient_id INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9F925F2B933FE08C ON recipe_ingredients (ingredient_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9F925F2B59D8A214 ON recipe_ingredients (recipe_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE recipes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, serve INT DEFAULT NULL, instructions JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A369E2B5A76ED395 ON recipes (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_ingredients ADD CONSTRAINT FK_9F925F2B933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_ingredients ADD CONSTRAINT FK_9F925F2B59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipes (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipes ADD CONSTRAINT FK_A369E2B5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_ingredients DROP CONSTRAINT FK_9F925F2B933FE08C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_ingredients DROP CONSTRAINT FK_9F925F2B59D8A214
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipes DROP CONSTRAINT FK_A369E2B5A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE ingredients
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE recipe_ingredients
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE recipes
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE users
        SQL);
    }
}
